image: ruby

before_script:
  - gem install bundler
  - bundle install

pages:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public --incremental
  artifacts:
    paths:
    - public
  only:
  - master
