# site settings
title: 👋 AlexMorris.dev
subtitle: 🧙 Open Sourcerer
email: hey@alexmorris.dev
description: Jack of all trades, master of most of 'em.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: localhost
city: Little Rock
state: AR
#zip_code: 55555
country: 🇺🇸
#phone: Leavin' Robocallers on read.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
#500px_url:
#facebook_url:
# github_url: https://github.com/matrix8967
gitlab_url: https://gitlab.com/matrix8967
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
mastodon_url: https://mastodon.social/@matrix8967

# build settings
markdown: kramdown

sass:
  style: compressed
