# site settings
title: 👋 Alex Morris
subtitle: I just wanna find what I love, and have it make me too big for my clothes.
email: hey@mainframe.computer
description: Guess there's nothing more elusive than obvious facts...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
#street_address:
#city: Little Rock
state: AR
#zip_code: 55555
country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/matrix8967
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
