# site settings
title: 👋 AlexMorris.dev
subtitle: Open Sourcerer
email: hey@mainframe.computer
description: Give me pieces of paper, and I will type things for you endlessly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
#street_address:
city: Little Rock
state: AR
#zip_code: 55555
country: United States of America
phone: Leavin' Robo Callers on read.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
#500px_url:
#facebook_url:
#github_url:
gitlab_url: https://gitlab.com/u/matrix8967
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
twitter_url: https://mastodon.social/@matrix8967

# build settings
markdown: kramdown

sass:
  style: compressed
